import PDFDocument from "pdfkit";
import { IIncident } from "./incident.model";

// ==========================================
// HELPERS
// ==========================================

const formatDate = (date?: Date | string) => {
  if (!date) {
    return "N/A";
  }

  return new Date(date).toLocaleString();
};

const getUserName = (user: any) => {
  if (!user) {
    return "Unassigned";
  }

  return user.name || user.email || "Unknown User";
};

// ==========================================
// GENERATE INCIDENT PDF
// ==========================================

export const generateIncidentPdf = (
  incident: IIncident
): PDFKit.PDFDocument => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    info: {
      Title: `Incident Report - ${incident.incidentId}`,
      Author: "ITSM Platform",
      Subject: "Incident Report",
    },
  });

  // ==========================================
  // HEADER
  // ==========================================

  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("ITSM INCIDENT REPORT", {
      align: "center",
    });

  doc.moveDown(0.5);

  doc
    .fontSize(11)
    .font("Helvetica")
    .text(`Incident ID: ${incident.incidentId}`, {
      align: "center",
    });

  doc.moveDown();

  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown();

  // ==========================================
  // BASIC INFORMATION
  // ==========================================

  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .text("Incident Information");

  doc.moveDown(0.5);

  addField(doc, "Title", incident.title);
  addField(doc, "Status", incident.status);
  addField(doc, "Priority", incident.priority);
  addField(doc, "Severity", incident.severity);

  doc.moveDown(0.5);

  // ==========================================
  // DESCRIPTION
  // ==========================================

  addSectionTitle(doc, "Description");

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(incident.description || "N/A", {
      align: "left",
      lineGap: 3,
    });

  doc.moveDown();

  // ==========================================
  // PEOPLE
  // ==========================================

  addSectionTitle(doc, "People");

  const reportedBy = (incident as any).reportedBy;
  const assignedTo = (incident as any).assignedTo;

  addField(
    doc,
    "Reported By",
    getUserName(reportedBy)
  );

  addField(
    doc,
    "Assigned To",
    getUserName(assignedTo)
  );

  // ==========================================
  // DATES
  // ==========================================

  addSectionTitle(doc, "Dates");

  addField(
    doc,
    "Created At",
    formatDate(incident.createdAt)
  );

  addField(
    doc,
    "Updated At",
    formatDate(incident.updatedAt)
  );

  addField(
    doc,
    "Resolved At",
    formatDate(incident.resolvedAt)
  );

  addField(
    doc,
    "Closed At",
    formatDate(incident.closedAt)
  );

  // ==========================================
  // RESOLUTION
  // ==========================================

  addSectionTitle(doc, "Resolution");

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      incident.resolution || "No resolution recorded.",
      {
        align: "left",
        lineGap: 3,
      }
    );

  // ==========================================
  // FOOTER
  // ==========================================

  doc
    .fontSize(8)
    .fillColor("gray")
    .text(
      "Generated by Enterprise IT Service Management Platform",
      50,
      760,
      {
        align: "center",
        width: 495,
      }
    );

  return doc;
};

// ==========================================
// FIELD HELPER
// ==========================================

const addField = (
  doc: PDFKit.PDFDocument,
  label: string,
  value: string
) => {
  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .fillColor("black")
    .text(`${label}: `, {
      continued: true,
    })
    .font("Helvetica")
    .text(value || "N/A");

  doc.moveDown(0.25);
};

// ==========================================
// SECTION TITLE HELPER
// ==========================================

const addSectionTitle = (
  doc: PDFKit.PDFDocument,
  title: string
) => {
  doc.moveDown(0.75);

  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .fillColor("black")
    .text(title);

  doc.moveDown(0.35);
};

// ==========================================
// DEFAULT EXPORT
// ==========================================

export default generateIncidentPdf;