import { format } from 'date-fns'
import { CheckCircle, Clock, User, XCircle } from 'lucide-react'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { StatusBadge } from '@/components/ui/status-badge'
import { getServiceRequestUserDisplay, normalizeServiceRequestStatus, type ServiceRequest } from '@/types/serviceRequest'

const date = (value?: string) => (value ? format(new Date(value), 'MMM d, yyyy HH:mm') : '—')
const Row = ({ label, value }: { label: string; value: string }) => <div className="flex items-start justify-between gap-4 py-2 text-sm"><span className="text-muted-foreground">{label}</span><span className="text-right">{value}</span></div>

export function ServiceRequestViewDialog({ open, onOpenChange, serviceRequest }: { open: boolean; onOpenChange: (open: boolean) => void; serviceRequest: ServiceRequest | null }) {
  if (!serviceRequest) return null
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{serviceRequest.requestId}</DialogTitle><DialogDescription className="text-base font-medium text-foreground">{serviceRequest.title}</DialogDescription></DialogHeader><div className="space-y-4"><div className="flex flex-wrap gap-3"><StatusBadge status={normalizeServiceRequestStatus(serviceRequest.status)}>{serviceRequest.status}</StatusBadge><StatusBadge status={serviceRequest.priority.toLowerCase()}>{serviceRequest.priority}</StatusBadge><StatusBadge status="outline">{serviceRequest.type}</StatusBadge></div><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Description</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm">{serviceRequest.description}</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><User className="h-4 w-4" />People</CardTitle></CardHeader><CardContent className="divide-y"><Row label="Requested by" value={getServiceRequestUserDisplay(serviceRequest.requestedBy)} /><Row label="Assigned to" value={getServiceRequestUserDisplay(serviceRequest.assignedTo)} /><Row label="Approved by" value={getServiceRequestUserDisplay(serviceRequest.approvedBy)} /></CardContent></Card>{serviceRequest.rejectionReason && <Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><XCircle className="h-4 w-4 text-destructive" />Rejection reason</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm">{serviceRequest.rejectionReason}</p></CardContent></Card>}<Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><Clock className="h-4 w-4" />Tracking</CardTitle></CardHeader><CardContent className="divide-y"><Row label="Created" value={date(serviceRequest.createdAt)} /><Row label="Last updated" value={date(serviceRequest.updatedAt)} />{serviceRequest.approvedAt && <Row label="Approved" value={date(serviceRequest.approvedAt)} />}{serviceRequest.startedAt && <Row label="Work started" value={date(serviceRequest.startedAt)} />}{serviceRequest.completedAt && <Row label="Completed" value={date(serviceRequest.completedAt)} />}{serviceRequest.rejectedAt && <Row label="Rejected" value={date(serviceRequest.rejectedAt)} />}{serviceRequest.cancelledAt && <Row label="Cancelled" value={date(serviceRequest.cancelledAt)} />}</CardContent></Card>{serviceRequest.status === 'Completed' && <div className="flex items-center gap-2 text-sm text-green-700"><CheckCircle className="h-4 w-4" />Request completed</div>}</div></DialogContent></Dialog>
}
